SELECT * 
  FROM `nyu-datathon.Team8.filtered_for_apache_version_hospital_prediction` f
LEFT JOIN `physionet-data.eicu_crd.intakeoutput` io
USING (patientunitstayid)
WHERE io.cellpath in ('flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % 1,000 mL with potassium chloride 20 mEq infusion' ,
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Lactated Ringers Volume',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % bolus 500 mL' ,
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 40 mEq/L infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 40 mEq/L infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS bolus',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-sodium chloride 0.9 % bolus 1,000 mL' ,
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-SODIUM CHLORIDE 0.9 % IV SOLN Pyxis Override',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS + ADD',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D10NS',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS w/20 mEq KCL',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS w/40 mEq KCL' ,
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS w/20 mEq KCL 1000 ml',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / sodium chloride 0.9% infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % / sodium chloride 0.9% infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % 500 mL IV bolus',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-0.9 % NaCl with KCl 40 mEq / L infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % flush IVPB 250 mL',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % flush IVPB 500 mL',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS c IVF',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS w/40 mEq KCL 1000 ml',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % 1,000 mL IV bolus' ,
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % and 0.9 % NaCl with KCl 20 mEq/L infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9 % with KCl 20 mEq infusion' ,
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS w/20 mEq KCL',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS KVO',   
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS 0.9% Volume',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.9 % sodium chloride with KCl 20 mEq/L',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS w/20 mEq KCL 1000 ml',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 %-0.9 % sodium chloride infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-dextrose 5 % and 0.9% NaCl infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-0.9 % NaCl with KCl 20 mEq/ L infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-0.9 % sodium chloride with potassium chloride 20 mEq/L infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|0.45 NS' ,
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-lactated ringers infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS b IVF',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-sodium chloride 0.9% infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5NS',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|Volume (mL)-0.9 % sodium chloride solution',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-0.9 % sodium chloride infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|NS',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|NS IVF',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-dextrose 5 % in lactated ringers infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|D5 LR',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Generic Intake (ml)|Volume (mL)-lactated ringers infusion',
                      'flowsheet|Flowsheet Cell Labels|I&O|Intake (ml)|Crystalloids (ml)|LR'); 